---
- name: 사용자 삭제
  hosts: web1.example.com
  vars_files:
    - secret.yml
  tasks:
    - name: user1 사용자 삭제
      user:
        name: "{{ username }}"
        state: absent
        remove: yes


- name: 사용자 삭제
  hosts: web2.example.com
  vars_files:
    - secret2.yml
  tasks:
    - name: user1 사용자 삭제
      user:
        name: "{{ username }}"
        state: absent
        remove: yes