---
- name: Restore playbook.yml
  hosts: all
  tasks:
    # 1) /etc/ansible/fact.d 디렉토리 삭제
    - name: /etc/ansible/fact.d remove directory
      file:
        path: /etc/ansible
        state: absent
    # 2) 웹 서비스 내리기
    - name: WEB service down
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: stopped
    # 3) 웹 패키지 삭제
    - name: WEB package remove
      yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: absent