---
- name: Configure dbservers
  hosts: dbservers
  tasks:
    - name: Import the variable file
      include_vars: paths.yml

    - name: Creates the Directory({{ paths.dbpath }})
      file:
        path: "{{ paths.dbpath }}"
        state: directory 
        mode: '0755'
      register: result

    - debug: var=result.path