---
- name: Install fileserver packages
  hosts: fileservers
  tasks:
    - name: variable Import
      include_vars: package.yml

    - name: Task Import
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: epel-release

    - name: Second Task Import
      include_tasks: install_package.yml
      vars:
        packages:
          web_pkg: tomcat       