---
- name: 방화벽, 웹서버 설정
  hosts: all
  tasks:
    # 1) 패키지 설치 - httpd, mod_ssl, firewalld
    # 2) 서비스 설정 - /var/www/html/index.html
    # 3) 서비스 기동 - httpd, firewalld
    # 4) 방화벽 등록 - http, https
    - name: 패키지 설치
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - mod_ssl
        - firewalld

    - name: 서비스 설정
      copy:
        src: /home/ansible/ansible/05_facts/file/index.html
        dest: /var/www/html/index.html

    - name: 서비스 기동
      service:
        name: "{{ item }}"
        state: started
      loop:
        - httpd
        - firewalld
    
    - name: 방화벽 등록
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https