---
- name: WEB-DB Service
  hosts: web1
  tasks:
    # 1) Install packages - Web(httpd, php, php-mysqlnd, php-pdo), db(mariadb-server), firewall(firewalld)
    # 2) Configure the web service - /var/www/html/index.php
    # 3) Enable Service - firewall, web(httpd), db(mariadb)
    # 4) Open the Service - http, https
    - name: Install packages - Web(firewalld, httpd, php, php-mysqlnd, php-pdo), db(mariadb-server), firewall(firewalld)
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server
          - firewalld
        state: present
    - name: Configure the web service - /var/www/html/index.php
      get_url:
        url: http://192.168.10.10/index.php
        dest: /var/www/html/index.php
    - name: Enable Service - firewall, web(httpd), db(mariadb)
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
    - name: Open the Service - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https


- name: Test Web Server
  hosts: localhost
  tasks:
    - name: Connect to Web Server
      uri:
        url: "http://web1.example.com"
        return_content: yes
        status_code: 200


