---
- name: Restore playbook.yml
  hosts: databases
  gather_facts: no
  tasks:
    - name: Disable Service
      service:
        name: mariadb
        state: stopped
        enabled: no
    - name: Remove packages
      yum:
        name: 
          - httpd
          - mariadb-server