---
- name: Restore playbook
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    - name: Service disable
      service:
        name: "{{ db_svc }}"
        state: stopped

    - name: Packages remove
      yum: 
        name: "{{ db_packages }}"
        state: absent