---
- name: 사용자 삭제
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: Creating users from secret.yml
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      with_items: "{{ newusers }}"
