---
- name: Make 
  hosts: fileserver
  tasks:
    - name: 파티션 설정 - sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [ lvm ]

    - name: 파티션 설정 - sdc
      parted:
        device: /dev/sdc
        number: 1
        state: present
        flags: [ lvm ]

    - name: LVM 작업
      lvg:
        vg: vg1
        pvs: /dev/sdb1,/dev/sdc1
    
    - name: LV 만들기 - lv1
      lvol:
        vg: vg1
        lv: lv1
        size: 512
    - name: LV 만들기 - lv2
      lvol:
        vg: vg1
        lv: lv2
        size: 1g

    - name: 파일 시스템 작업 - lv1
      filesystem:
        fstype: ext4
        dev: /dev/vg1/lv1
    - name: 파일 시스템 작업 - lv2
      filesystem:
        fstype: xfs
        dev: /dev/vg1/lv2

    - name: 마운트 디렉토리 생성
      file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      with_items:
        - /mnt
        - /mnt/lv1
        - /mnt/lv2

    - name: 마운트 작업
      mount:
        path: /mnt/lv1
        src: /dev/vg1/lv1
        fstype: ext4
        state: mounted
    - name: 마운트 작업
      mount:
        path: /mnt/lv2
        src: /dev/vg1/lv2
        fstype: xfs
        state: mounted
        