---
- name: MAKE Mail server
  hosts: all
  tasks:
    - name: Mail task
      include: configure_mail.yml

  handlers:
    - name: start_postfix
      service:
        name: postfix
        state: started

    - name: start_dovecot  
      service:
        name: dovecot
        state: started 

    - name: restart_postfix
      service:
        name: postfix
        state: restarted