---
- name: Configure /etc/motd file
  hosts: all
  gather_facts: yes
  vars:
    - system_owner: webmaster@example.com
  tasks:
    - name: Deploy /etc/motd    
      template:
        src: template/motd.j2
        dest: /etc/motd
      